// flow-typed signature: 4a7eed5807c35fe358c22fa7dd821598
// flow-typed version: <<STUB>>/base64-inline-loader_v^1.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base64-inline-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base64-inline-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'base64-inline-loader/index' {
  declare module.exports: $Exports<'base64-inline-loader'>;
}
declare module 'base64-inline-loader/index.js' {
  declare module.exports: $Exports<'base64-inline-loader'>;
}
