// flow-typed signature: 4fcd8360c8352cedbfb717f16dad0c0a
// flow-typed version: <<STUB>>/browser-sync-webpack-plugin_v^1.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-sync-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-sync-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'browser-sync-webpack-plugin/index' {
  declare module.exports: $Exports<'browser-sync-webpack-plugin'>;
}
declare module 'browser-sync-webpack-plugin/index.js' {
  declare module.exports: $Exports<'browser-sync-webpack-plugin'>;
}
