// flow-typed signature: 05c7021216a72c1120d82ecc70193cf4
// flow-typed version: <<STUB>>/documentation-loader_v^0.1.1-beta/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'documentation-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'documentation-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'documentation-loader/dist/documentation-loader' {
  declare module.exports: any;
}

declare module 'documentation-loader/lib/documentation-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'documentation-loader/dist/documentation-loader.js' {
  declare module.exports: $Exports<'documentation-loader/dist/documentation-loader'>;
}
declare module 'documentation-loader/lib/documentation-loader.js' {
  declare module.exports: $Exports<'documentation-loader/lib/documentation-loader'>;
}
