// flow-typed signature: 012b37aebc5c2b9115e78e1786ee04fd
// flow-typed version: <<STUB>>/growl_v^1.10.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'growl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'growl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'growl/lib/growl' {
  declare module.exports: any;
}

declare module 'growl/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'growl/lib/growl.js' {
  declare module.exports: $Exports<'growl/lib/growl'>;
}
declare module 'growl/test.js' {
  declare module.exports: $Exports<'growl/test'>;
}
