// flow-typed signature: 80e590cfe85da9b4eaaf17c495823817
// flow-typed version: <<STUB>>/jsdoc-webpack-plugin_v0.0.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jsdoc-webpack-plugin/index' {
  declare module.exports: $Exports<'jsdoc-webpack-plugin'>;
}
declare module 'jsdoc-webpack-plugin/index.js' {
  declare module.exports: $Exports<'jsdoc-webpack-plugin'>;
}
