// flow-typed signature: a4c8f74e689d37288b4924faa792e648
// flow-typed version: <<STUB>>/postcss-easysprites_v^0.1.8/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-easysprites'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-easysprites' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-easysprites/index' {
  declare module.exports: $Exports<'postcss-easysprites'>;
}
declare module 'postcss-easysprites/index.js' {
  declare module.exports: $Exports<'postcss-easysprites'>;
}
