// flow-typed signature: 6567379fd7be12f67b28eb6bd9ff69a0
// flow-typed version: <<STUB>>/postcss-simple-extend_v^1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-simple-extend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-simple-extend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-simple-extend/index' {
  declare module.exports: $Exports<'postcss-simple-extend'>;
}
declare module 'postcss-simple-extend/index.js' {
  declare module.exports: $Exports<'postcss-simple-extend'>;
}
