// flow-typed signature: a447781bf252366b631a5873b55c0f81
// flow-typed version: <<STUB>>/postcss-inline-image_v^0.1.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-inline-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-inline-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-inline-image/index' {
  declare module.exports: $Exports<'postcss-inline-image'>;
}
declare module 'postcss-inline-image/index.js' {
  declare module.exports: $Exports<'postcss-inline-image'>;
}
