// flow-typed signature: 8956dd9b3fa4f5c801ed5ebc642c9562
// flow-typed version: <<STUB>>/postcss-image-inliner_v^2.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-image-inliner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-image-inliner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-image-inliner/lib/image' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-image-inliner/index' {
  declare module.exports: $Exports<'postcss-image-inliner'>;
}
declare module 'postcss-image-inliner/index.js' {
  declare module.exports: $Exports<'postcss-image-inliner'>;
}
declare module 'postcss-image-inliner/lib/image.js' {
  declare module.exports: $Exports<'postcss-image-inliner/lib/image'>;
}
