// flow-typed signature: 6e5d531d0015e5432c97c8c5193ab5f9
// flow-typed version: <<STUB>>/style-ext-html-webpack-plugin_v^3.4.7/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-ext-html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-ext-html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-ext-html-webpack-plugin/lib/common' {
  declare module.exports: any;
}

declare module 'style-ext-html-webpack-plugin/lib/config' {
  declare module.exports: any;
}

declare module 'style-ext-html-webpack-plugin/lib/findFile' {
  declare module.exports: any;
}

declare module 'style-ext-html-webpack-plugin/lib/insertStyle' {
  declare module.exports: any;
}

declare module 'style-ext-html-webpack-plugin/lib/plugin' {
  declare module.exports: any;
}

declare module 'style-ext-html-webpack-plugin/lib/removeFile' {
  declare module.exports: any;
}

declare module 'style-ext-html-webpack-plugin/lib/replaceTag' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-ext-html-webpack-plugin/index' {
  declare module.exports: $Exports<'style-ext-html-webpack-plugin'>;
}
declare module 'style-ext-html-webpack-plugin/index.js' {
  declare module.exports: $Exports<'style-ext-html-webpack-plugin'>;
}
declare module 'style-ext-html-webpack-plugin/lib/common.js' {
  declare module.exports: $Exports<'style-ext-html-webpack-plugin/lib/common'>;
}
declare module 'style-ext-html-webpack-plugin/lib/config.js' {
  declare module.exports: $Exports<'style-ext-html-webpack-plugin/lib/config'>;
}
declare module 'style-ext-html-webpack-plugin/lib/findFile.js' {
  declare module.exports: $Exports<'style-ext-html-webpack-plugin/lib/findFile'>;
}
declare module 'style-ext-html-webpack-plugin/lib/insertStyle.js' {
  declare module.exports: $Exports<'style-ext-html-webpack-plugin/lib/insertStyle'>;
}
declare module 'style-ext-html-webpack-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'style-ext-html-webpack-plugin/lib/plugin'>;
}
declare module 'style-ext-html-webpack-plugin/lib/removeFile.js' {
  declare module.exports: $Exports<'style-ext-html-webpack-plugin/lib/removeFile'>;
}
declare module 'style-ext-html-webpack-plugin/lib/replaceTag.js' {
  declare module.exports: $Exports<'style-ext-html-webpack-plugin/lib/replaceTag'>;
}
