// flow-typed signature: 9f92dc0c72fbc8ee370f15c76f2f273a
// flow-typed version: <<STUB>>/webpack-logging-plugin_v^0.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-logging-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-logging-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-logging-plugin/lib/util/clearConsole' {
  declare module.exports: any;
}

declare module 'webpack-logging-plugin/lib/util/displayErrors' {
  declare module.exports: any;
}

declare module 'webpack-logging-plugin/lib/util/getProgressMessage' {
  declare module.exports: any;
}

declare module 'webpack-logging-plugin/lib/util/registerCompilerCallbacks' {
  declare module.exports: any;
}

declare module 'webpack-logging-plugin/lib/WebpackLoggingPlugin' {
  declare module.exports: any;
}

declare module 'webpack-logging-plugin/src/util/clearConsole' {
  declare module.exports: any;
}

declare module 'webpack-logging-plugin/src/util/displayErrors' {
  declare module.exports: any;
}

declare module 'webpack-logging-plugin/src/util/getProgressMessage' {
  declare module.exports: any;
}

declare module 'webpack-logging-plugin/src/util/registerCompilerCallbacks' {
  declare module.exports: any;
}

declare module 'webpack-logging-plugin/src/WebpackLoggingPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-logging-plugin/lib/util/clearConsole.js' {
  declare module.exports: $Exports<'webpack-logging-plugin/lib/util/clearConsole'>;
}
declare module 'webpack-logging-plugin/lib/util/displayErrors.js' {
  declare module.exports: $Exports<'webpack-logging-plugin/lib/util/displayErrors'>;
}
declare module 'webpack-logging-plugin/lib/util/getProgressMessage.js' {
  declare module.exports: $Exports<'webpack-logging-plugin/lib/util/getProgressMessage'>;
}
declare module 'webpack-logging-plugin/lib/util/registerCompilerCallbacks.js' {
  declare module.exports: $Exports<'webpack-logging-plugin/lib/util/registerCompilerCallbacks'>;
}
declare module 'webpack-logging-plugin/lib/WebpackLoggingPlugin.js' {
  declare module.exports: $Exports<'webpack-logging-plugin/lib/WebpackLoggingPlugin'>;
}
declare module 'webpack-logging-plugin/src/util/clearConsole.js' {
  declare module.exports: $Exports<'webpack-logging-plugin/src/util/clearConsole'>;
}
declare module 'webpack-logging-plugin/src/util/displayErrors.js' {
  declare module.exports: $Exports<'webpack-logging-plugin/src/util/displayErrors'>;
}
declare module 'webpack-logging-plugin/src/util/getProgressMessage.js' {
  declare module.exports: $Exports<'webpack-logging-plugin/src/util/getProgressMessage'>;
}
declare module 'webpack-logging-plugin/src/util/registerCompilerCallbacks.js' {
  declare module.exports: $Exports<'webpack-logging-plugin/src/util/registerCompilerCallbacks'>;
}
declare module 'webpack-logging-plugin/src/WebpackLoggingPlugin.js' {
  declare module.exports: $Exports<'webpack-logging-plugin/src/WebpackLoggingPlugin'>;
}
