// flow-typed signature: 5425689f265d5526b28c438974a04385
// flow-typed version: <<STUB>>/webpack-format-messages_v^1.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-format-messages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-format-messages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-format-messages/index' {
  declare module.exports: $Exports<'webpack-format-messages'>;
}
declare module 'webpack-format-messages/index.js' {
  declare module.exports: $Exports<'webpack-format-messages'>;
}
