// flow-typed signature: 428a4883e388c0d016fc5baccca9e08f
// flow-typed version: <<STUB>>/webpack-error-notification_v^0.1.7/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-error-notification'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-error-notification' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-error-notification/index' {
  declare module.exports: $Exports<'webpack-error-notification'>;
}
declare module 'webpack-error-notification/index.js' {
  declare module.exports: $Exports<'webpack-error-notification'>;
}
